psp:
  url: '${PSP_CLIENT_URL:https://sandbox-reporting.rpdpymnt.com/api/v3}'
  authentication-token-expire-time: 585000 # 9 min 45 second
  credentials:
    email: '${PSP_CLIENT_EMAIL:demo@financialhouse.io}'
    password: '${PSP_CLIENT_PASSWORD:cjaiU8CV}'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html