psp:
  url: https://sandbox-reporting.rpdpymnt.com/api/v3
  authentication-token-expire-time: 585000 # 9 min 45 second
  credentials:
    email: demo@financialhouse.io
    password: cjaiU8CV

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html